---
- name: Change password for existing users
  hosts: all
  become: yes
  vars_files:
    - passwords_vars.yml
  tasks:
    - name: Change password for users
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        update_password: always
      loop: "{{ users }}"
    - name: Add Asateel user to sudoers file
      copy:
        dest: "/etc/sudoers.d/rex"
        content: "rex ALL=(ALL) NOPASSWD: ALL"
        mode: '0440'
